services:
  # ------------------------------
  # Postgres + DB
  # ------------------------------
  mlflow-db:
    image: postgres:17
    env_file:
      - .env.postgres  
    ports:
      - 5432:5432
    volumes:
      - mlflow_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mlflow"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # ------------------------------
  # Minio + bucket
  # ------------------------------

  minio:
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    env_file:
      - .env.minio 
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"

  # ------------------------------
  # MLFlow (Tracking server a model registry)
  # ------------------------------
  mlflow:
    build:
      context: ./mlflow
    platform: linux/amd64
    restart: always
    environment:
      BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-db:5432/${POSTGRES_DB}
      ARTIFACT_ROOT: /mlflow/artifacts
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    env_file:
      - .env.aws
      - .env.postgres
    volumes:
      - ./mlruns:/mlflow/artifacts
    ports:
      - "5500:5000"   # host:container, changed host port to 5500
    depends_on:
      - mlflow-db
      - minio
    command: >
      mlflow server
      --backend-store-uri ${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-db:5432/${POSTGRES_DB}
      --default-artifact-root s3://mlflow
      --host 0.0.0.0
      --port 5000

  # ------------------------------
  # Prefect (Workflow Orchestration)
  # ------------------------------
  # prefect:
  #   image: prefecthq/prefect:2-latest
  #   platform: linux/amd64
  #   ports:
  #     - "4200:4200"
  #   environment:
  #     PREFECT_ORION_DATABASE_CONNECTION_URL: postgresql+asyncpg://mlflow:mlflow@mlflow-db:5432/mlflow
  #   command: prefect server start --host 0.0.0.0 --port 4200

  # ------------------------------
  # FastAPI Model Serving
  # ------------------------------
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    env_file:
      - .env.aws
    volumes:
      - ./mlruns:/mlflow/artifacts
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

volumes:
  mlflow_db: