services:
  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    env_file:
      - .env.aws 
    volumes:
      - ./trainer:/app
    command: python train.py