services:
  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_SECRET_ACCESS_KEY: minio_password
      AWS_ACCESS_KEY_ID: minio_user
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000 
    volumes:
      - ./trainer:/app
    command: python train.py